#!/usr/bin/env lua
require "ipv4"
require "ipv6"
require "usage"

if arg[1] and arg[2] then
	ip_class = IPv4
	if arg[3] then
		if arg[3] == "-ipv6" then
			ip_class = IPv6
		elseif arg[3] == "-ipv4" then
			ip_class = IPv4
		else
			print("Invalid argument: "..arg[3])
			print()
			print_usage()
			os.exit(1)
		end
	end
	ip1 = newIP(arg[1], ip_class)
	ip2 = newIP(arg[2], ip_class)
	if ip1 and ip2 then
		print(ip1:range_to(ip2))
	else
		if not ip1 then
			print("Argument IP1 Invalid!")
		end 
		if not ip2 then
			print("Argument IP2 Invalid!")
		end
		print()
		print_usage()
		os.exit(1)
	end
else
	print_usage()
	os.exit(1)
end
os.exit(0)